import { GameType } from "@prisma/client";

export const REALM_TO_METADATA: Record<
  GameType,
  { region: string; displayName: string; id: string }[]
> = {
  [GameType.NORMAL]: [
    { region: "us", displayName: "Angerforge", id: "angerforge" },
    { region: "us", displayName: "Arugal", id: "arugal" },
    { region: "us", displayName: "Ashkandi", id: "ashkandi" },
    { region: "us", displayName: "Atiesh", id: "atiesh" },
    { region: "us", displayName: "Azuresong", id: "azuresong" },
    { region: "us", displayName: "Benediction", id: "benediction" },
    { region: "us", displayName: "Bloodsail Buccaneers", id: "bloodsail-buccaneers" },
    { region: "us", displayName: "Earthfury", id: "earthfury" },
    { region: "us", displayName: "Eranikus", id: "eranikus" },
    { region: "us", displayName: "Faerlina", id: "faerlina" },
    { region: "us", displayName: "Grobbulus", id: "grobbulus" },
    { region: "us", displayName: "Maladath", id: "maladath" },
    { region: "us", displayName: "Mankrik", id: "mankrik" },
    { region: "us", displayName: "Myzrael", id: "myzrael" },
    { region: "us", displayName: "Old Blanchy", id: "old-blanchy" },
    { region: "us", displayName: "Pagle", id: "pagle" },
    { region: "us", displayName: "Remulos", id: "remulos" },
    { region: "us", displayName: "Skyfury", id: "skyfury" },
    { region: "us", displayName: "Sulfuras", id: "sulfuras" },
    { region: "us", displayName: "Westfall", id: "westfall" },
    { region: "us", displayName: "Whitemane", id: "whitemane" },
    { region: "us", displayName: "Windseeker", id: "windseeker" },
    { region: "us", displayName: "Yojamba", id: "yojamba" },
    { region: "eu", displayName: "Amnennar", id: "amnennar" },
    { region: "eu", displayName: "Ashbringer", id: "ashbringer" },
    { region: "eu", displayName: "Auberdine", id: "auberdine" },
    { region: "eu", displayName: "Chromie", id: "chromie" },
    { region: "eu", displayName: "Earthshaker", id: "earthshaker" },
    { region: "eu", displayName: "Everlook", id: "everlook" },
    { region: "eu", displayName: "Firemaw", id: "firemaw" },
    { region: "eu", displayName: "Flamegor", id: "flamegor" },
    { region: "eu", displayName: "Gehennas", id: "gehennas" },
    { region: "eu", displayName: "Giantstalker", id: "giantstalker" },
    { region: "eu", displayName: "Golemagg", id: "golemagg" },
    { region: "eu", displayName: "Hydraxian Waterlords", id: "hydraxian-waterlords" },
    { region: "eu", displayName: "Jin'do", id: "jin'do" },
    { region: "eu", displayName: "Lakeshire", id: "lakeshire" },
    { region: "eu", displayName: "Mandokir", id: "mandokir" },
    { region: "eu", displayName: "Mirage Raceway", id: "mirage-raceway" },
    { region: "eu", displayName: "Mograine", id: "mograine" },
    { region: "eu", displayName: "Nethergarde Keep", id: "nethergarde-keep" },
    { region: "eu", displayName: "Patchwerk", id: "patchwerk" },
    { region: "eu", displayName: "Pyrewood Village", id: "pyrewood-village" },
    { region: "eu", displayName: "Razorfen", id: "razorfen" },
    { region: "eu", displayName: "Sulfuron", id: "sulfuron" },
    { region: "eu", displayName: "Thekal", id: "thekal" },
    { region: "eu", displayName: "Transcendence", id: "transcendence" },
    { region: "eu", displayName: "Venoxis", id: "venoxis" },
    // MOP
    { region: "us", displayName: "Galakras", id: "galakras" },
    { region: "us", displayName: "Immerseus", id: "immerseus" },
    { region: "us", displayName: "Lei Shen", id: "lei-shen" },
    { region: "us", displayName: "Nazgrim", id: "nazgrim" },
    { region: "us", displayName: "Ra-den", id: "ra-den" },
    { region: "eu", displayName: "Garalon", id: "garalon" },
    { region: "eu", displayName: "Hoptallus", id: "hoptallus" },
    { region: "eu", displayName: "Norushen", id: "norushen" },
    { region: "eu", displayName: "Ook Ook", id: "ook-ook" },
    { region: "eu", displayName: "Shek'zeer", id: "shekzeer" },
  ],
  [GameType.ERA]: [
    { region: "us", displayName: "Anathema", id: "anathema" },
    { region: "us", displayName: "Arcanite Reaper", id: "arcanite-reaper" },
    { region: "us", displayName: "Arugal", id: "arugal" },
    { region: "us", displayName: "Ashkandi", id: "ashkandi" },
    { region: "us", displayName: "Atiesh", id: "atiesh" },
    { region: "us", displayName: "Azuresong", id: "azuresong" },
    { region: "us", displayName: "Benediction", id: "benediction" },
    { region: "us", displayName: "Bigglesworth", id: "bigglesworth" },
    { region: "us", displayName: "Blaumeux", id: "blaumeux" },
    { region: "us", displayName: "Bloodsail Buccaneers", id: "bloodsail-buccaneers" },
    { region: "us", displayName: "Deviate Delight", id: "deviate-delight" },
    { region: "us", displayName: "Earthfury", id: "earthfury" },
    { region: "us", displayName: "Faerlina", id: "faerlina" },
    { region: "us", displayName: "Fairbanks", id: "fairbanks" },
    { region: "us", displayName: "Felstriker", id: "felstriker" },
    { region: "us", displayName: "Grobbulus", id: "grobbulus" },
    { region: "us", displayName: "Heartseeker", id: "heartseeker" },
    { region: "us", displayName: "Herod", id: "herod" },
    { region: "us", displayName: "Incendius", id: "incendius" },
    { region: "us", displayName: "Kirtonos", id: "kirtonos" },
    { region: "us", displayName: "Kromcrush", id: "kromcrush" },
    { region: "us", displayName: "Kurinnaxx", id: "kurinnaxx" },
    { region: "us", displayName: "Loatheb", id: "loatheb" },
    { region: "us", displayName: "Mankrik", id: "mankrik" },
    { region: "us", displayName: "Myzrael", id: "myzrael" },
    { region: "us", displayName: "Netherwind", id: "netherwind" },
    { region: "us", displayName: "Old Blanchy", id: "old-blanchy" },
    { region: "us", displayName: "Pagle", id: "pagle" },
    { region: "us", displayName: "Rattlegore", id: "rattlegore" },
    { region: "us", displayName: "Remulos", id: "remulos" },
    { region: "us", displayName: "Skeram", id: "skeram" },
    { region: "us", displayName: "Skull Rock", id: "skull-rock" },
    { region: "us", displayName: "Smolderweb", id: "smolderweb" },
    { region: "us", displayName: "Stalagg", id: "stalagg" },
    { region: "us", displayName: "Sul'thraze", id: "sul'thraze" },
    { region: "us", displayName: "Sulfuras", id: "sulfuras" },
    { region: "us", displayName: "Thalnos", id: "thalnos" },
    { region: "us", displayName: "Thunderfury", id: "thunderfury" },
    { region: "us", displayName: "Westfall", id: "westfall" },
    { region: "us", displayName: "Whitemane", id: "whitemane" },
    { region: "us", displayName: "Windseeker", id: "windseeker" },
    { region: "us", displayName: "Yojamba", id: "yojamba" },
    // EU
    { region: "eu", displayName: "Amnennar", id: "amnennar" },
    { region: "eu", displayName: "Ashbringer", id: "ashbringer" },
    { region: "eu", displayName: "Auberdine", id: "auberdine" },
    { region: "eu", displayName: "Bloodfang", id: "bloodfang" },
    { region: "eu", displayName: "Celebras", id: "celebras" },
    { region: "eu", displayName: "Dragon's Call", id: "dragons-call" },
    { region: "eu", displayName: "Dragonfang", id: "dragonfang" },
    { region: "eu", displayName: "Dreadmist", id: "dreadmist" },
    { region: "eu", displayName: "Earthshaker", id: "earthshaker" },
    { region: "eu", displayName: "Everlook", id: "everlook" },
    { region: "eu", displayName: "Finkle", id: "finkle" },
    { region: "eu", displayName: "Firemaw", id: "firemaw" },
    { region: "eu", displayName: "Flamelash", id: "flamelash" },
    { region: "eu", displayName: "Gandling", id: "gandling" },
    { region: "eu", displayName: "Lucifron", id: "lucifron" },
    { region: "eu", displayName: "Mandokir", id: "mandokir" },
    { region: "eu", displayName: "Mirage Raceway", id: "mirage-raceway" },
    { region: "eu", displayName: "Mograine", id: "mograine" },
    { region: "eu", displayName: "Nethergarde Keep", id: "nethergarde-keep" },
    { region: "eu", displayName: "Noggenfogger", id: "noggenfogger" },
    { region: "eu", displayName: "Patchwerk", id: "patchwerk" },
    { region: "eu", displayName: "Pyrewood Village", id: "pyrewood-village" },
    { region: "eu", displayName: "Razorfen", id: "razorfen" },
    { region: "eu", displayName: "Razorgore", id: "razorgore" },
    { region: "eu", displayName: "Shazzrah", id: "shazzrah" },
    { region: "eu", displayName: "Skullflame", id: "skullflame" },
    { region: "eu", displayName: "Stonespine", id: "stonespine" },
    { region: "eu", displayName: "Sulfuron", id: "sulfuron" },
    { region: "eu", displayName: "Ten Storms", id: "ten-storms" },
    { region: "eu", displayName: "Transcendence", id: "transcendence" },
    { region: "eu", displayName: "Venoxis", id: "venoxis" },
    { region: "eu", displayName: "Wyrmthalak", id: "wyrmthalak" },
  ],
  [GameType.SEASONAL]: [
    { region: "us", displayName: "Chaos Bolt", id: "chaos-bolt" },
    { region: "us", displayName: "Crusader Strike", id: "crusader-strike" },
    { region: "us", displayName: "Lava Lash", id: "lava-lash" },
    { region: "us", displayName: "Living Flame", id: "living-flame" },
    { region: "us", displayName: "Lone Wolf", id: "lone-wolf" },
    { region: "us", displayName: "Penance (AU)", id: "penance-au" },
    { region: "us", displayName: "Shadowstrike (AU)", id: "shadowstrike-au" },
    { region: "us", displayName: "Wild Growth", id: "wild-growth" },
    // eu
    { region: "eu", displayName: "Chaos Bolt", id: "chaos-bolt" },
    { region: "eu", displayName: "Crusader Strike", id: "crusader-strike" },
    { region: "eu", displayName: "Lava Lash", id: "lava-lash" },
    { region: "eu", displayName: "Living Flame", id: "living-flame" },
    { region: "eu", displayName: "Lone Wolf", id: "lone-wolf" },
    { region: "eu", displayName: "Penance (RU)", id: "penance-ru" },
    { region: "eu", displayName: "Shadowstrike (RU)", id: "shadowstrike-ru" },
    { region: "eu", displayName: "Wild Growth", id: "wild-growth" },
  ],
  [GameType.HARDCORE]: [
    { region: "us", displayName: "Defias Pillager", id: "defias-pillager" },
    { region: "us", displayName: "Skull Rock", id: "skull-rock" },
    // EU
    { region: "eu", displayName: "Nek'Rosh", id: "nekrosh" },
    { region: "eu", displayName: "Stitches", id: "stitches" },
  ],
};

export function getGameType(realmName: string, isEra: boolean): GameType {
  if (!isEra) {
    return GameType.NORMAL;
  }

  if (REALM_TO_METADATA.SEASONAL.find((r) => r.id === realmName)) {
    return GameType.SEASONAL;
  }

  if (REALM_TO_METADATA.ERA.find((r) => r.id === realmName)) {
    return GameType.ERA;
  }

  if (REALM_TO_METADATA.HARDCORE.find((r) => r.id === realmName)) {
    return GameType.HARDCORE;
  }
  throw new Error("Error: Realm not found");
}
